TestPlatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('api/', include('api.urls', namespace='apitest')),
    path('product/', include('product.urls', namespace='product')),
    path('bug/', include('bug.urls', namespace='bug')),
    path('app/', include('app.urls', namespace='app')),
    path('web/', include('web.urls', namespace='web')),
    path('manage/', include('django_sb_admin.urls', namespace='manage')),
    path('tool/', include('tool.urls', namespace='tool'))
]

account/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/15 下午12:04
# @Author  : zhouyajun
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout')
]

api/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/15 下午12:10
# @Author  : zhouyajun
from django.urls import path
from api import views

app_name = 'apitest'

urlpatterns = [
    path('cases/', views.api_test_manage, name='api_case_manage'),
    path('step/', views.api_step_manage, name='step_manage'),
    path('manage/', views.api_manage, name='api_manage')
]

product/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/15 下午2:40
# @Author  : zhouyajun
from django.urls import path
from product import views
app_name = 'product'

urlpatterns = [
    path('manage/', views.product_manage, name='manage')
]

product/models.py
from django.db import models


# Create your models here.


class Product(models.Model):
    product_name = models.CharField('产品名称', max_length=64)
    product_desc = models.CharField('产品描述', max_length=200)
    producter = models.CharField('产品负责人', max_length=200)
    create_time = models.DateTimeField('创建时间', auto_now=True)

    class Meta:
        verbose_name = '产品管理'
        verbose_name_plural = '产品管理'

    def __str__(self):
        return self.product_name

    def __repr__(self):
        return 'Product<product_name:{}>'.format(self.product_name)


class Env(models.Model):
    name = models.CharField('环境名称', max_length=20)
    env_url = models.CharField('环境URL', max_length=50)
    url = models.URLField('URL', max_length=60)

    def __str__(self):
        return self.name

    def __repr__(self):
        return 'Env<{}>'.format(self.name)

    class Meta:
        verbose_name = '环境访问地址'
        verbose_name_plural = '环境访问地址'


class Version(models.Model):
    version = models.CharField('版本', max_length=30)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = '版本号'
        verbose_name_plural = '版本号'


class DataBaseConfig(models.Model):
    db_name = models.CharField('数据库名称', max_length=50)
    db_host = models.CharField('数据库地址', max_length=100)
    db_port = models.IntegerField('端口')
    db_user = models.CharField('用户', max_length=20)
    db_pwd = models.CharField('密码', max_length=30)

    def __str__(self):
        return self.db_name

    class Meta:
        verbose_name = '数据库'
        verbose_name_plural = '数据库'

product/views.py
from django.shortcuts import render

# Create your views here.
from product.models import Product


def product_manage(request):
    username = request.session.get('user')
    products = Product.objects.all()
    return render(request, 'product/product_manage.html',
                  {"user": username, "products": products, 'nav_active': 'product'})

product/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>产品自动化测试平台</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body role="document">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fix-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-center"></ul>
        <ul class="nav justify-content-end">
            <li class="navbar-link">
                <a style="color: white" href="#">{{ user }}</a>
            </li>
            <li class="navbar-link">
                <a style="color: white" href="{% url 'account:logout' %}">退出</a>
            </li>
        </ul>
    </div>
</nav>

{% block product_list %}

{% endblock %}
</body>
</html>

product/templates/product_manage.html
{% extends 'base.html' %}
{% block product_list %}
    <div class="row" style="padding-top: 20px">
        <div class="col-md-11">
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <th>ID</th>
                    <th>产品名称</th>
                    <th>产品描述</th>
                    <th>产品负责人</th>
                    <th>创建时间</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.id }}</td>
                        <td>{{ product.product_name }}</td>
                        <td>{{ product.product_desc }}</td>
                        <td>{{ product.producter }}</td>
                        <td>{{ product.create_time }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}