TestPlatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('api/', include('api.urls', namespace='apitest')),
    path('product/', include('product.urls', namespace='product')),
    path('bug/', include('bug.urls', namespace='bug')),
    path('app/', include('app.urls', namespace='app')),
    path('web/', include('web.urls', namespace='web')),
    path('manage/', include('django_sb_admin.urls', namespace='manage')),
    path('tool/', include('tool.urls', namespace='tool'))
]

api/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/15 下午12:10
# @Author  : zhouyajun
from django.urls import path
from api import views

app_name = 'apitest'

urlpatterns = [
    path('cases/', views.api_test_manage, name='api_case_manage'),
    path('step/', views.api_step_manage, name='step_manage'),
    path('manage/', views.api_manage, name='api_manage')
]

django_sb_admin/urls.py
from django.urls import path

import django_sb_admin.views
app_name = 'manage'

urlpatterns = [

    path('', django_sb_admin.views.index, name='sb_admin_index'),
    path('dashboard/', django_sb_admin.views.dashboard, name='sb_admin_dashboard'),
    path('charts/', django_sb_admin.views.charts, name='sb_admin_charts'),
    path('tables/', django_sb_admin.views.tables, name='sb_admin_tables'),
    path('forms/', django_sb_admin.views.forms, name='sb_admin_forms'),
    path('bootstrap-elements/', django_sb_admin.views.bootstrap_elements, name='sb_admin_bootstrap_elements'),
    path('bootstrap-grid/', django_sb_admin.views.bootstrap_grid, name='sb_admin_bootstrap_grid'),
    path('rtl-dashboard/', django_sb_admin.views.rtl_dashboard, name='sb_admin_rtl_dashboard'),
    path('blank/', django_sb_admin.views.blank, name='sb_admin_blank'),
    path('login/', django_sb_admin.views.login, name='login'),
]

product/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/15 下午2:40
# @Author  : zhouyajun
from django.urls import path
from product import views
app_name = 'product'

urlpatterns = [
    path('manage/', views.product_manage, name='manage')
]

product/models.py
from django.db import models


# Create your models here.


class Product(models.Model):
    product_name = models.CharField('产品名称', max_length=64)
    product_desc = models.CharField('产品描述', max_length=200)
    producter = models.CharField('产品负责人', max_length=200)
    create_time = models.DateTimeField('创建时间', auto_now=True)

    class Meta:
        verbose_name = '产品管理'
        verbose_name_plural = '产品管理'

    def __str__(self):
        return self.product_name

    def __repr__(self):
        return 'Product<product_name:{}>'.format(self.product_name)


class Env(models.Model):
    name = models.CharField('环境名称', max_length=20)
    env_url = models.CharField('环境URL', max_length=50)
    url = models.URLField('URL', max_length=60)

    def __str__(self):
        return self.name

    def __repr__(self):
        return 'Env<{}>'.format(self.name)

    class Meta:
        verbose_name = '环境访问地址'
        verbose_name_plural = '环境访问地址'


class Version(models.Model):
    version = models.CharField('版本', max_length=30)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = '版本号'
        verbose_name_plural = '版本号'


class DataBaseConfig(models.Model):
    db_name = models.CharField('数据库名称', max_length=50)
    db_host = models.CharField('数据库地址', max_length=100)
    db_port = models.IntegerField('端口')
    db_user = models.CharField('用户', max_length=20)
    db_pwd = models.CharField('密码', max_length=30)

    def __str__(self):
        return self.db_name

    class Meta:
        verbose_name = '数据库'
        verbose_name_plural = '数据库'

product/views.py
from django.shortcuts import render

# Create your views here.
from product.models import Product


def product_manage(request):
    username = request.session.get('user')
    products = Product.objects.all()
    return render(request, 'product/product_manage.html',
                  {"user": username, "products": products, 'nav_active': 'product'})

templates/product/product_base.html
{% extends 'base.html' %}
{% block content %}
{% block product_list %}

{% endblock %}
{% endblock %}

templates/product/product_manage.html
{% extends "django_sb_admin/base.html" %}{% load static %}{% block sb_admin_title %}产品管理{% endblock sb_admin_title %}
{% block sb_admin_subheading %}{% endblock sb_admin_subheading %}
{% block sb_admin_breadcrumb %}<i class="fa fa-dashboard"></i>
    <a href="{% url 'manage:sb_admin_index' %}">Dashboard</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_breadcrumb_active %}
    <li class="active">
        <i class="fa fa-table"></i> 产品管理
    </li>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>产品名称</th>
                        <th>产品描述</th>
                        <th>产品负责人</th>
                        <th>创建时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product in products %}
                        <tr>
                            <td>{{ product.id }}</td>
                            <td>{{ product.product_name }}</td>
                            <td>{{ product.product_desc }}</td>
                            <td>{{ product.producter }}</td>
                            <td>{{ product.create_time }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}